### ISSUE TITLE
Bug-Suggestion List

### ISSUE THREAD

**Issue by furkanalptokac** [brk007/Sparkle_Of_Last_Hope#1]
1- Some characters won't die when they killed (Animation).
2- Dialog box can appear when you get closer to a NPC and a text like "Press Q to Talk".
3- Some characters can't attack.
4- Our character can't attack sometimes when you talk someone.
5- Our character is drifting.
6- Some campfires won't heal you.

**Comment by brk007** [comment]
1- My codes work perfectly but it happens on random enemies in each game which i don't know why.
2- I added this to the game.
3- Fixed.
4- Fixed.
5- I don't know how to do this on unity. Unity supports 2D and 3D but my game is 2.5D genre so probably unity don't has feature for that. If it has please enlighten me.
6- Fixed.
